
= Projektauftrag: Rennverwaltung

=== Projektauftraggeber
* HTBLA Leonding, Auftraggeber: Herr Prof. Aitenbichler

=== Autor
* Saydam Arda, Kurtic Ademir

=== Projekthintergrund
* Die aktuelle Rennverwaltung leidet unter Mängeln bei der Festlegung von Autos und Bedienern an den Stationen während der Rennveranstaltungen. Dies führt zu Unklarheiten und möglichen Störungen während des Rennens.

|===
| Phase | Meilenstein / Ergebnis | Soll-Termin | Freigabe

| Mockups erstellen | fertige Mockups | 03.03.2024 | -
| Use-Cases erstellen | fertige Use-Cases | 15.03.2024 | -
| Projektstruktur erstellen|fertige Struktur|17.04.2024|-
| Projektstruktur überarbeiten|fertige Projektstruktur|01.05.2024|-
|===

=== Mengengerüst

* Programm läuft immer.


=== Projektergebnis
Das Ergebnis des Projekts ist eine übersichtliche Benutzeroberfläche, die es ermöglicht, die Autos und Bedienern an den Stationen während der Rennveranstaltungen zu verwalten. Die Benutzeroberfläche soll einfach zu bedienen sein und eine klare Übersicht über die Rennen bieten.

=== Projektziel
Das Ziel ist es, eine Ordnung und Übersicht in die Verwaltung der Rennen bezüglich der benutzten Autos und Bedienern zu bringen. Dies soll durch eine übersichtliche Benutzeroberfläche und eine einfache Bedienung erreicht werden.

=== Projektorganisation
==== Projektleiter
* Saydam Arda
