@startuml
class Race {
    -RaceId: Number
}

class Car {
    -carId: Number
    -carName: String
    
}

class Obstacle {
    -obstacleId: Number
    -obstacleName: String
}

class Input {
    -inputId: Number
    -inputName: String
}

Input->Race
Car->Race
Obstacle->Race
@enduml
